accounts/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

from .views import SignupView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignupView.as_view(), name='signup'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('news.urls')),
    path('accounts/', include('accounts.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

news/urls.py
from django.urls import URLPattern, path
from news import views

urlpatterns = [
    path('', views.index_view, name='index'),
    path('book/<str:book_title>/detail/', views.detail_book_view, name='detail-book'),
    path('book/create/', views.Create_Book_View, name='create-book'),
    path('book/<str:book_review_title>/review', views.CreateReviewView.as_view(), name='review'),
    path('book/search/', views.Search_Book, name='search'),
    path('book/Narrow_down/business/', views.Categorize_by_business, name='narrow-down-business'),
    path('book/Narrow_down/science・Technology/', views.Categorize_by_science_and_Technology, name='narrow-down-science・Technology'),
    path('book/Narrow_down/Humanities・ideas/', views.Categorize_by_Humanities_and_ideas, name='narrow-down-Humanities・ideas'),
    path('book/Narrow_down/computer・IT/', views.Categorize_by_computer_and_IT, name='narrow-down-computer・IT'),
    
]

news/models.py
from django.db import models
from news.consts import MAX_RATE
# Create your models here.




CATEGORY = (('business', 'ビジネス'), ('science ・Technology', '科学・テクノロジー'), ('Humanities ・ ideas', '人文・思想'), ('computer・IT', 'コンピュータ・IT'))
RATE_CHOICES = [(x, str(x))for x in range(0, MAX_RATE + 1)]

class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=200, null=True)
    price = models.IntegerField(null=True)
    book_url = models.URLField(null=True)
    book_image_url = models.URLField(null=True)
    book_contents = models.CharField(max_length=5000, null=True)
    publisherName = models.CharField(max_length=100, null=True)
    salesDate = models.CharField(max_length=100, null=True)
    subtitle = models.CharField(max_length=1000, null=True)
    category = models.CharField(
        max_length = 100,
        choices = CATEGORY
    )
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    
    def __str__(self):
        return self.title


class Review(models.Model):
    book = models.ForeignKey(to=Book, on_delete=models.CASCADE, related_name='reviews')
    title = models.CharField(max_length=100)
    text = models.TextField()
    rate = models.IntegerField(choices=RATE_CHOICES)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)

    def __str__(self):
        return self.title

news/forms.py
from cProfile import label
from django import forms
from .models import Book

class BookForm(forms.ModelForm):
      class Meta:
            model = Book
            fields = ('title', 'category')
            labels = {
                'title': '対象書籍 :',
                'category': 'カテゴリ :'

            }
            widgets = {
                'title': forms.TextInput(attrs={'placeholder':'書籍のタイトルを入力'}),
            }

news/views.py
import environ
from django.shortcuts import render, redirect
from django.urls import  reverse
from django.db.models import Avg, Q
from django.views.generic import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from news.models import  Book, Review
from django.core.paginator import Paginator
from news.forms import BookForm
import requests
from news.consts import ITEM_PER_PAGE
from apiclient.discovery import build

# Create your views here.

env = environ.Env()
env.read_env('.env')

REQUEST_URL = 'https://app.rakuten.co.jp/services/api/BooksBook/Search/20170404'
APP_ID = env('APP_ID', str)

YOUTUBE_DATE_API_ID = env('YOUTUBE_DATE_API_ID', str)

DEVELOPER_KEY = YOUTUBE_DATE_API_ID
YOUTUBE_API_SERVICE_NAME = "youtube"
YOUTUBE_API_VERSION = "v3"

GOOGLE_API_KEY = env('GOOGLE_API_KEY', str)

CUSTOM_SEARCH_ENGINE_ID = env('CUSTOM_SEARCH_ENGINE_ID', str)



def index_view(request):
    indexview = IndexView()
    book_list = indexview.get_top_page_book_date(request)
    paginator = Paginator(book_list, ITEM_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    context = {
        'page_obj': page_obj,
    }
    
    
   
    return render(request, 'book/index.html', context)
    



def detail_book_view(request, book_title):

    detailbookview = DetailBooKView(book_title)
    book_information_list = detailbookview.get_detail_book_date()

    try:
        youtube_video_url_dict = detailbookview.get_youtube_video_url()
    except UnboundLocalError:
        youtube_video_url_dict.clear()

    except KeyError:
        youtube_video_url_dict.clear()
        
    Google_search_result_date_url = detailbookview.get_Google_search_result_date_url()
    Twitter_url_to_search = detailbookview.get_Twitter_url_date_to_search()
    note_url_to_search = detailbookview.get_note_url_date_to_search()
    review_book_list = detailbookview.get_review_book_date()
    
    
    context = {
        'page_obj': book_information_list,
        'book_title':book_title,
        'youtube_video_url_dict': youtube_video_url_dict,  
        'Google_search_result_date_url': Google_search_result_date_url,
        'Twitter_url_to_search': Twitter_url_to_search,
        'note_url_to_search' : note_url_to_search,
        'review_book_list': review_book_list,
        
    }
     
    return render(request, 'book/book_detail.html', context)



def Create_Book_View(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            obj = Book()
            form = BookForm(request.POST, instance=obj)
            if form.is_valid():
                form.instance.user = request.user
                form.save()
                return redirect(to='index')

    else:
        return redirect(to='accounts:login')
        

    context = {
        'BookForm': BookForm(),
   }
    
    return render(request, 'book/book_create.html', context)
    


class CreateReviewView(LoginRequiredMixin, CreateView):
    template_name = 'book/review_form.html'
    model = Review
    fields = ('book', 'title', 'text', 'rate')
    
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['book'] = Book.objects.filter(title__icontains=self.kwargs['book_review_title'])
        return context
    
    def form_valid(self, form):
        form.instance.user = self.request.user

        return super().form_valid(form)

    def get_success_url(self, **kwargs):
        return reverse('index')
   


def Search_Book(request):
    object_list = Book.objects.order_by('-id')
    keyword = request.GET.get('keyword')
    if keyword:
        object_list = object_list.filter(
            Q(title__icontains=keyword)
        )
        messages.success(request, '{}の検索結果'.format(keyword))
    
    
    paginator = Paginator(object_list, ITEM_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    

    context = {
        'page_obj': page_obj,
    }


    return render(request, 'book/book_search.html', context)

        
    
def Categorize_by_business(request):

    object_list = Book.objects.filter(category='business')
    paginator = Paginator(object_list, ITEM_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    context = {
        'page_obj': page_obj,
    }
    
    return render(request, 'book/categorize_by_category.html' ,context)
    

def Categorize_by_science_and_Technology(request):
    
    object_list = Book.objects.filter(category='science ・Technology')
    paginator = Paginator(object_list, ITEM_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    
    context = {
        'page_obj': page_obj,
    }
    
    
    return render(request, 'book/categorize_by_category.html' ,context)


def Categorize_by_Humanities_and_ideas(request):
    
    object_list = Book.objects.filter(category='Humanities ・ ideas')
    paginator = Paginator(object_list, ITEM_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
   
    context = {
        'page_obj': page_obj,
    }
    
    return render(request, 'book/categorize_by_category.html' ,context)

def Categorize_by_computer_and_IT(request):
  
    object_list = Book.objects.filter(category='computer・IT')
    paginator = Paginator(object_list, ITEM_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    context = {
        'page_obj': page_obj,
    }
    
    
    return render(request, 'book/categorize_by_category.html' ,context)


class IndexView(object):

    def get_top_page_book_date(self, request):
        if Book.objects.filter(author__isnull=True).exists():
            object_list = Book.objects.filter(author__isnull=True)
    
            book_information_list = []
            book_title = []
            for object in object_list:
                paramas = {
                'applicationId': APP_ID,
                'format': 'json',
                'title': object.title,
            }
                book_title.append(object.title)
                try:
                    response = requests.get(REQUEST_URL, paramas).json()["Items"][0]['Item']
                except Exception:
                    object_list.delete()
                    messages.error(request, f'{object.title} は登録することができない書籍です。')
                    continue
                
                if Book.objects.filter(title__icontains=response['title'] ,author__icontains=response['author']).exists():
                    object_list.delete()
                    messages.error(request, f'{object.title} はすでに登録されている書籍です。')
                    continue

                for key in list(response):
                    if not key in ['title', 'author', 'itemCaption', 'itemPrice', 'itemUrl', 'largeImageUrl', 'publisherName',  'salesDate', 'subTitle']:
                        del response[key]
  
                book_information_list.append(response)


        
            for index, book in enumerate(book_information_list):

                obj, created = Book.objects.update_or_create(

                title=book_title[index],
                defaults={
                    'title': book['title'],
                    'author': book['author'],
                    'price': book['itemPrice'],
                    'book_url': book['itemUrl'],
                    'salesDate': book['salesDate'],
                    'book_contents': book['itemCaption'], 
                    'publisherName': book['publisherName'],
                    'book_image_url': book['largeImageUrl'], 
                    'subtitle': book['subTitle']
                    }

                )


                

        book_list = Book.objects.all().order_by('-id')

        

        return book_list


class DetailBooKView(object):
    
    def __init__(self, book_title) -> None:
        self.book_title = book_title
        
    

    def get_detail_book_date(self):
        object_list = Book.objects.filter(title__icontains=self.book_title)
        
        
        return object_list

    def get_youtube_video_url(self):
        youtube = build(YOUTUBE_API_SERVICE_NAME, YOUTUBE_API_VERSION, developerKey=DEVELOPER_KEY)
        youtube_video_url_dict = {}


        search_response = youtube.search().list(
            part="snippet",
            maxResults=5,
            q=self.book_title,
        )
        

        search_response = search_response.execute()['items']
        

        for search_result in search_response:

            youtube_title = search_result['snippet']['title']
            try:
                youtube_video_id = search_result['id']['videoId']

            except UnboundLocalError:
                pass

            except KeyError:
                pass
            try:
                youtube_video_url = f'https://www.youtube.com/watch?v={youtube_video_id}'

            except UnboundLocalError:
                pass

            except KeyError:
                pass
            try:
                youtube_video_url_dict[youtube_title] = youtube_video_url
            except UnboundLocalError:
                pass
                
        return youtube_video_url_dict

    def get_Google_search_result_date_url(self):
        Google_search_result_date_url = {}
        keyword = f'{self.book_title} 要約'  

        search_book_review_date = build('customsearch',
                'v1',
                developerKey=GOOGLE_API_KEY)

        result_book_review_date = search_book_review_date.cse().list(q=keyword,
                        cx=CUSTOM_SEARCH_ENGINE_ID,
                        lr='lang_ja',
                        num=10,
                        start=1).execute()

        result_book_review_date = result_book_review_date['items']


        
        

news/templates/book/base.html
{% load static %}
<!doctype html>
    <html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

        <title>{% block title %}{% endblock title %}|本棚アプリ</title>
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    </head>
    <body>
        

        <!-- Optional JavaScript; choose one of the two! -->

        <!-- Option 1: Bootstrap Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

        <!-- Option 2: Separate Popper and Bootstrap JS -->
        <!--
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
        -->
        <header class="sticky-top">
          <nav class="navbar navbar-expand-lg navbar-dark bg-success">
              <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'index' %}"><img src="{% static 'image/Book.jpg' %}" style="border-radius: 10%; width: 60px; height: 46px; margin-left: 10px;"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarScroll">
                  <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                    <li class="nav-item">
                      <a class="nav-link" aria-current="page" href="{% url 'create-book' %}">書籍登録</a>
                    </li>
                    <div class="navbar-nav d-flex flex-row">
                        {% if request.user.is_authenticated %}
                          <a class="nav-link"  href="{% url 'accounts:logout' %}">ログアウト</a>
                        {% else %}
                          <a class="nav-link"  href="{% url 'accounts:login' %}">ログイン</a>
                          <br>
                          <a class="nav-link"  href="{% url 'accounts:signup'%}">会員登録</a>
                        {% endif %}
                    </div>
                    <li class="nav-item dropdown"> 
                      <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        絞り込み
                      </a> 
                      <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">

                        <li><a class="dropdown-item" href="#">カテゴリ</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="{% url 'narrow-down-business' %}">・ビジネス</a></li>
                        <li><a class="dropdown-item" href="{% url 'narrow-down-science・Technology' %}">・科学・テクノロジー</a></li>
                        <li><a class="dropdown-item" href="{% url 'narrow-down-Humanities・ideas' %}">・人文・思想</a></li>
                        <li><a class="dropdown-item" href="{% url 'narrow-down-computer・IT' %}">・コンピュータ・IT</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><hr class="dropdown-divider"></li>
                      </ul>
                    </li>
                  </ul>
                  <form class="d-flex" action="{% url 'search'%}" method="get">
                    <input class="form-control me-2" type="search" placeholder="書籍のタイトルを入力" aria-label="Search" name="keyword" value="{{ request.GET.keyword}}" required>
                    <button class="btn btn-outline-success" type="submit">Search</button>
                  </form>
                </div>
              </div>
          </nav>
        </header>
        
        {% if messages %}
          <ul class="messages_ul">
            {% for message in messages %}
              <li class="alert{% if message.tags %} alert-{{ message.tags }}{% endif %}" role="alert">{{ message }}</li>
            {% endfor %}
          </ul>
        {% endif %}

        <div class="p-4">
          <h1>{% block h1 %} {% endblock %}</h1>
          {% block content %} {% endblock content %}
        </div>
    </body>
</html>

news/templates/book/book_confirm_delete.html
{% extends 'book/base.html' %}

{% block title %}レビュー投稿{% endblock %}
{% block h1%} レビュー投稿{% endblock %}
{%block content%}
    
    <form method="post" class="p-4 m-4 bg-light border border-success rounded form-group">
    {% csrf_token %}
    {% for item in book %}
        <table>
            <tr>
                <th>
                    <label>対象書籍</label>
                </th>
                <th>
                    <input class="form-contorl" value="{{ item.title }}" readonly>
                </th>
            </tr>
            <tr>
                <th>
                    <label>
                        タイトル
                    </label>
                </th>
                <th>
                    <input class="form-contorol" name="title">
                </th>
            </tr>
        </table>
        <label>
            本文
        </label>
        <textarea class="form-control" name="text" rows="3"></textarea>
        <label>
            星の数
        </label>
        <select class="form-control" name="rate">
            <option value="0">0 (最低)</option>
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3" selected>3 (普通)</option>
            <option value="4">4</option>
            <option value="5">5 (最高)</option>
        </select>
        <input type="hidden" name="book" value="{{ item.id }}">
        <button type="submit" class="btn btn-success mt-4">投稿する</button>
    {% endfor %}
    </form>

{% endblock %}

news/templates/book/book_create.html
{% extends 'book/base.html' %}

{% block title %} 書籍作成 {% endblock title %}  

{% block content %}
    <h1>書籍新規登録</h1>
    <form method='POST' action="{% url 'create-book' %}" enctype="multipart/form-data" class=" m-4 bg-light border-success rounded form-group">
        {% csrf_token %}
            
            {{ BookForm.as_p }}
            <p><button type="submit" class="btn btn-success mt-4">作成する</button></p>
    </form>

{% endblock content%}

news/templates/book/book_detail.html
{% extends 'book/base.html' %}
{% load extra_tags %}
{% load static %}


{% block title %} {{ object.title }} {% endblock title %}
{% block h1 %}書籍詳細{% endblock %}

{% block content %}

    <div class="p-4 m-4 bg-light border border-success rounded">
        {% for book_obj in page_obj %}
            <h2 class="text-success">{{ book_obj.title }}</h2>
            <br>
            <a href=""><img src="{{ book_obj.book_image_url }}" class="img-thumbnail"></a>
            <br>
            <br>
            <h6>著者</h6>
            <hr>
            <p style="margin-left: 5px;">{{ book_obj.author}}</p>
            <br>
            <h6>価格</h6>
            <hr>
            <p style="margin-left: 5px;">￥{{ book_obj.price}}</p>
            <br>
            <h6>内容</h6>
            <hr>
            <p style="margin-left: 5px;">{{ book_obj.book_contents}}</p>
            <br>
            <h6>出版社</h6>
            <hr>
            <p style="margin-left: 5px;">{{ book_obj.publisherName }}</p>
            <br>
            <h6>発売日</h6>
            <hr>
            <p style="margin-left:5px;">{{ book_obj.salesDate }}</p>
            <br>
            <h6>書籍購入</h6>
            <hr>
            <a href="{{ book_obj.book_url }}"><img src="{% static 'image/楽天.jpg' %}" style="width: 100px; height: 55px"></a>
            <a href="https://www.amazon.co.jp/?&tag=hydraamazonav-22&ref=pd_sl_7ibq2d37on_e&adgrpid=56100363354&hvpone=&hvptwo=&hvadid=592007363477&hvpos=&hvnetw=g&hvrand=12297889841017896830&hvqmt=e&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=1009552&hvtargid=kwd-10573980&hydadcr=27922_14541005&gclid=Cj0KCQjwjvaYBhDlARIsAO8PkE1HwEE9tEvPqUhl2qtwplY8-vQGr9hfhBzLSz1ptbEk7FjDy1xzLc0aAkLQEALw_wcB"><img src="{% static 'image/amazon.jpg' %}" style="width: 100px; height: 55px" ></a>
            <a href="https://jp.mercari.com/"><img src="{% static 'image/mercari.jpg' %}" style="width: 100px; height: 60px" ></a>
            <a href="https://auctions.yahoo.co.jp/?cpt_s=onlineads&cpt_m=websem&cpt_c=webgkt&cpt_n=17470362622_aud-303767875568:kwd-10755383427_615399667164&gclid=Cj0KCQjwjvaYBhDlARIsAO8PkE0gWZv4PIFYfdcqoyZQIEI_0-37_lIhY3y3ptsewHDbok_Vi6DfQNgaAhc1EALw_wcB"><img src="{% static 'image/ヤフオク.jpg' %}" style="width: 100px; height: 60px" ></a>
            <a href="https://paypayfleamarket.yahoo.co.jp/"><img src="{% static 'image/PayPayフリマ.png' %}" style="width: 200px; height: 60px"></a>
            <br>
            <br>
        {% endfor %}
        <h6>{{ book_title }}でYouTube検索</h6>
        <hr>
        {% if not youtube_video_url_dict %}
            <h6 style="color:gray; margin-left: 5px;">{{ book_title }}にあてはまる動画はありません。</h6>
        {% else %}
            {% for title, url in youtube_video_url_dict.items %}
                    <ui>
                        <p style="margin-left: 5px;"><a href="{{ url }}">{{ title }}</a></p>
                    </ui>
            {% endfor %}
        {% endif %}
        <br>
        <h6>{{ book_title }} 要約でGoogle検索</h6>
        <hr>
        {% for title, url in Google_search_result_date_url.items %}
                <ui>
                    <p style="margin-left: 5px;"><a href="{{ url }}">{{ title }}</a></p>
                </ui>
        {% endfor %}
        <br>
        <h6> {{ book_title }} でTwitter検索</h6>
        <hr>
        <a href="{{ Twitter_url_to_search }}"><img src="{% static 'image/twitter.png' %}" style="width:90px; height: 55px; margin-bottom: 30px;"></a>
        <br>
        <h6> {{ book_title }} でnote検索</h6>
        <hr>
        <a href="{{ note_url_to_search }}"><img src="{% static 'image/note.jpg' %}" style="width:90px; height: 55px; margin-bottom: 30px; border: solid #f5f5f5;"></a>
        <h6>すべてのレビュー</h6>
        <hr>
        <div class="border p-4 mb-2">
            {% if not review_book_list %}
                <h6 style="color:gray">現在レビューはありません</h6>
            {% else %}
                {% for review in review_book_list %}
                    <div>
                        <h3 class="h4">{{ review.title }}</h3>
                        <div class="px-2">
                            <span>投稿ユーザー: {{ review.user.username }}</span>
                            <br>
                            <h6>評価: {{ review.rate }}点</h6>
                            <p>{{ review.text }}</p>
                        </div>
                    </div>
                    <hr>
                {% endfor %}
            {% endif %}
        </div>
        <a href="{% url 'index' %}" class="btn btn-primary">一覧へ</a>
        <a href="{% url 'review' book_review_title=book_title %}" class="btn btn-primary">レビューする</a>
    </div>
{% endblock content%}

news/templates/book/book_search.html
{% extends 'book/base.html' %}
{% load extra_tags %}

{% block title %} 書籍一覧 {% endblock title %}
{% block h1 %}  書籍一覧　{% endblock %}

{% block content %}
<div class="row">
    <div class="col-lg-12 col-md-auto col-sm-auto">
    {% for book_obj in page_obj %}
        <div class="p-4 m-4 bg-light border border-success rounded">
            <h2 class="text-success">{{ book_obj.title }}</h2>
            <br>
            <a href="{{ book_obj.book_url }}"><img src="{{ book_obj.book_image_url }}" class="img-thumbnail" ></a>
            <div class="mt-3">
            <br>
            <a href="{% url 'detail-book' book_title=book_obj.title %}" class="btn btn-primary">詳細へ</a>
            </div>
        </div>
    {% endfor %}
    {% include 'book/components/pagination.html' %}
    </div >
</div>

{% endblock content%}

news/templates/book/categorize_by_category.html
{% extends 'book/base.html' %}
{% load extra_tags %}

{% block title %} 書籍一覧 {% endblock title %}
{% block h1 %}  書籍一覧　{% endblock %}

{% block content %}
<div class="row">
    <div class="col-lg-12 col-md-auto col-sm-auto">
    {% for book_obj in page_obj %}
        <div class="p-4 m-4 bg-light border border-success rounded">
            <h2 class="text-success">{{ book_obj.title }}</h2>
            <br>
            <a href="{{ book_obj.book_url }}"><img src="{{ book_obj.book_image_url }}" class="img-thumbnail" ></a>
            <div class="mt-3">
            <br>
            <a href="{% url 'detail-book' book_title=book_obj.title %}" class="btn btn-primary">詳細へ</a>
            </div>
        </div>
    {% endfor %}
    {% include 'book/components/pagination.html' %}
    </div >
</div>

{% endblock content%}

news/templates/book/index.html
{% extends 'book/base.html' %}
{% load extra_tags %}

{% block title %} 書籍一覧 {% endblock title %}
{% block h1 %}  書籍一覧　{% endblock %}
col-lg-12 col-md-auto col-sm-auto
{% block content %}
<div class="row">
    <div class="col-lg-12 col-md-auto col-sm-auto">
    {% for book_obj in page_obj %}
        <div class="p-4 m-4 bg-light border border-success rounded">
            <h2 class="text-success">{{ book_obj.title }}</h2>
            <br>
            <a href="{{ book_obj.book_url }}"><img src="{{ book_obj.book_image_url }}" class="img-thumbnail" ></a>
            <div class="mt-3">
            <br>
            <a href="{% url 'detail-book' book_title=book_obj.title %}" class="btn btn-primary">詳細へ</a>
            </div>
        </div>
    {% endfor %}
    {% include 'book/components/pagination.html' %}
    </div >
</div>

{% endblock content%}

news/templates/book/review_form.html
{% extends 'book/base.html' %}

{% block title %}レビュー投稿{% endblock %}
{% block h1%} レビュー投稿{% endblock %}
{%block content%}
    
    <form method="post" class="p-4 m-4 bg-light border border-success rounded form-group">
    {% csrf_token %}
    {% for item in book %}
        <table>
            <tr>
                <th>
                    <label>対象書籍</label>
                </th>
                <th>
                    <input class="form-contorl" value="{{ item.title }}" readonly>
                </th>
            </tr>
            <tr>
                <th>
                    <label>
                        タイトル
                    </label>
                </th>
                <th>
                    <input class="form-contorol" name="title">
                </th>
            </tr>
        </table>
        <label>
            本文
        </label>
        <textarea class="form-control" name="text" rows="3"></textarea>
        <label>
            星の数
        </label>
        <select class="form-control" name="rate">
            <option value="0">0 (最低)</option>
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3" selected>3 (普通)</option>
            <option value="4">4</option>
            <option value="5">5 (最高)</option>
        </select>
        <input type="hidden" name="book" value="{{ item.id }}">
        <button type="submit" class="btn btn-success mt-4">投稿する</button>
    {% endfor %}
    </form>

{% endblock %}